[package]
name = "graveler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
rand = "0.8.5"
tinyrand = "0.5.0"

[profile.release]
lto = 'fat'
opt-level = 3
codegen-units = 1
